version: '3.8'

services:
  todo-db:
    image: postgres:17
    container_name: todo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-backend:
    build: .
    container_name: todo-backend
    depends_on:
      - todo-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  todo-frontend:
    build:
      context: C:\Users\rezan\OneDrive\Masaüstü\todo-frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - todo-backend


volumes:
  postgres_data:
